{
  // 是否添加尾随逗号
  "trailingComma": "none",
  // 是否在每个语句的末尾添加分号
  "semi": false,
  // 超过这个长度，Prettier会自动换行
  "printWidth": 120,
  // 使用单引号包裹字符串
  "singleQuote": true,
  // 箭头函数时是否在参数周围添加括号
  // avoid:尽量避免
  // always:总是在箭头函数参数周围添加括号
  "arrowParens": "avoid"
}
